#!/bin/bash

mkdir compiled
cp *.lua compiled
mkdir compiled/func
cp func/*.lua compiled/func
mkdir compiled/assets
cp -r assets/* compiled/assets

rm pixelfinity.love
cd compiled
zip -r ../pixelfinity.love *

rm -rf compiled
